#!/usr/bin/env bash
set -euo pipefail

if ! command -v firebase >/dev/null 2>&1; then
  echo "firebase CLI not found. Install with: npm install -g firebase-tools"
  exit 1
fi

if ! firebase projects:list >/dev/null 2>&1; then
  echo "Firebase login required. Run: firebase login"
  exit 1
fi

REPO_NAME="$(basename "$(pwd)")"
CANDIDATE="${REPO_NAME,,}"
CANDIDATE="$(echo "$CANDIDATE" | tr -c 'a-z0-9' '-')"
CANDIDATE="${CANDIDATE#-}"
CANDIDATE="${CANDIDATE%-}"
if [ -z "$CANDIDATE" ]; then
  CANDIDATE="twin-growth-tracker"
fi

PROJECT_ID="${1:-$CANDIDATE}"

exists_project() {
  firebase projects:list 2>/dev/null | awk '{print $1}' | grep -qx "$1"
}

if exists_project "$PROJECT_ID"; then
  i=1
  while exists_project "${PROJECT_ID}-${i}"; do
    i=$((i+1))
  done
  PROJECT_ID="${PROJECT_ID}-${i}"
fi

echo "Creating Firebase project: $PROJECT_ID"
firebase projects:create "$PROJECT_ID"

cat > .firebaserc <<EOF
{
  "projects": {
    "default": "$PROJECT_ID"
  }
}
EOF

echo "Creating web app..."
APP_NAME="twin-growth-tracker"
APP_OUTPUT="$(firebase apps:create web "$APP_NAME" --project "$PROJECT_ID")"
APP_ID="$(echo "$APP_OUTPUT" | sed -n 's/.*App ID: //p' | head -n1 | tr -d '\r')"
if [ -z "$APP_ID" ]; then
  echo "Failed to detect App ID from firebase apps:create output."
  exit 1
fi

mkdir -p docs

echo "Fetching sdk config..."
TMP_FILE="$(mktemp)"
export TMP_FILE
firebase apps:sdkconfig WEB "$APP_ID" -o "$TMP_FILE"

python - <<'PY'
import json, os, sys
tmp = os.environ.get("TMP_FILE")
if not tmp or not os.path.exists(tmp):
    sys.exit("Missing sdkconfig file")
with open(tmp, "r", encoding="utf-8") as f:
    config = json.load(f)
js = "// Auto-generated by scripts/bootstrap_firebase.sh\n" \
     "export const firebaseConfig = " + json.dumps(config, indent=2) + ";\n"
with open(os.path.join("docs", "firebase-config.js"), "w", encoding="utf-8") as f:
    f.write(js)
PY

echo "Initialize Firestore (interactive). Choose Firestore only when prompted."
firebase init firestore

echo "Next manual steps:"
echo "1) Create Firestore database and select location (if not created)."
echo "2) Enable Anonymous Auth in Firebase console."
